module.exports = {
  apps: [
    {
      name: "weather-scheduler-v2",
      cwd: ".",
      script: "./scheduler.py",
      interpreter: "python3",
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      min_uptime: "30s",
      max_restarts: 100,
      kill_timeout: 10000,
      max_memory_restart: "1G",
      time: true,
      out_file: "logs/scheduler-out.log",
      error_file: "logs/scheduler-error.log",
      merge_logs: true,
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "weather-api-v2",
      cwd: ".",
      script: "./run_api.py",
      interpreter: "python3",
      autorestart: true,
      watch: false,
      restart_delay: 3000,
      min_uptime: "10s",
      max_restarts: 50,
      kill_timeout: 10000,
      max_memory_restart: "1G",
      time: true,
      out_file: "logs/api-out.log",
      error_file: "logs/api-error.log",
      merge_logs: true,
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
  ],
}
